import {
  AgentDefinition,
  Trace,
  PlatformKPIs,
  IntegrationStatus,
  AdminUser,
  AuditEvent,
  MetricPoint,
} from "./adminTypes";

export const MOCK_PLATFORM_KPIS: PlatformKPIs = {
  requests24h: 18420,
  escalationRate: 0.038, // 3.8%
  avgOrchestratorLatencyMs: 184,
  mcpAllowCount24h: 44912,
  mcpDenyCount24h: 38,
  activeAgentsCount: 11,
  dailyDisputedVolumeINR: 324500,
};

export const MOCK_AGENTS: AgentDefinition[] = [
  // CS Specialist Agents
  {
    id: "cs-orchestrator",
    name: "Customer Support Autonomous Orchestrator",
    category: "Core Orchestrator",
    purpose: "Central supervisor receiving merchant and customer messages, intent classification, and specialist dispatch.",
    stageOwnership: "Root Hub (Dispatches to all CS Specialists)",
    mcpAgentId: "agent_orchestrator_main",
    status: "healthy",
    allowedTools: [
      { toolName: "delegate_to_specialist", description: "Routes context to specialist agent", actionScope: "WRITE" },
      { toolName: "classify_intent", description: "Categorizes customer prompt against intent taxonomy", actionScope: "READ" },
      { toolName: "read_customer_session", description: "Accesses authenticated merchant memory", actionScope: "READ" },
    ],
    prohibitedTools: [
      { toolName: "direct_payment_refund", whyBlocked: "Orchestrators cannot execute financial transfers; must delegate to Payment or Escalation agent." },
      { toolName: "bypass_mcp_safety", whyBlocked: "Strict security invariant: All tool calls must pass through MCP boundary." },
    ],
    n8nWorkflowRef: "WF-CS-SUPERVISOR-V4",
    requests24h: 18420,
    avgLatencyMs: 82,
    errorRate: 0.001,
    enforcementStory: "The Orchestrator maintains dialogue context and state transitions but delegates specialized tool execution exclusively to domain specialists.",
  },
  {
    id: "orders-accounts-agent",
    name: "Orders & Accounts Agent",
    category: "Customer Support",
    purpose: "Queries transaction state, invoice receipts, and terminal binding records.",
    stageOwnership: "Transaction State & Order Verification",
    mcpAgentId: "agent_orders_v2",
    status: "healthy",
    allowedTools: [
      { toolName: "fetch_order_by_id", description: "Retrieves order status, UTR, and amount from ledger", actionScope: "READ" },
      { toolName: "fetch_customer_orders", description: "Queries paginated order list for merchant MID", actionScope: "READ" },
      { toolName: "verify_terminal_pairing", description: "Validates terminal assignment to order", actionScope: "READ" },
    ],
    prohibitedTools: [
      { toolName: "payment_refund", whyBlocked: "OrdersAgent is read-only for ledger history; cannot initiate money movement." },
      { toolName: "transaction_lookup_global", whyBlocked: "Scoped strictly to authenticated merchant's tenant; cannot query global bank switch." },
    ],
    n8nWorkflowRef: "WF-ORDERS-LEDGER-LOOKUP",
    requests24h: 6240,
    avgLatencyMs: 110,
    errorRate: 0.002,
    enforcementStory: "OrdersAgent enforces tenant isolation. It cannot query global bank switches or execute ledger debit/credit modifications.",
  },
  {
    id: "customer-rag-agent",
    name: "Customer RAG Memory Agent",
    category: "Customer Support",
    purpose: "Retrieves merchant profile, historical disputes, segment tier, and merchant-specific memory.",
    stageOwnership: "Merchant Context Enrichment",
    mcpAgentId: "agent_customer_rag",
    status: "healthy",
    allowedTools: [
      { toolName: "search_customer_memory", description: "Semantic vector search across merchant interaction logs", actionScope: "READ" },
      { toolName: "read_merchant_profile", description: "Loads MID, KYC status, and settlement bank details", actionScope: "READ" },
    ],
    prohibitedTools: [
      { toolName: "write_compliance_policy", whyBlocked: "Customer RAG agent has read-only access to merchant memory." },
    ],
    n8nWorkflowRef: "WF-CUSTOMER-MEMORY-V1",
    requests24h: 5120,
    avgLatencyMs: 95,
    errorRate: 0.001,
    enforcementStory: "Provides contextual personalization to prevent merchants from repeating details during multi-turn support sessions.",
  },
  {
    id: "knowledge-agent",
    name: "Knowledge Agent",
    category: "Customer Support",
    purpose: "General FAQ, product manuals, SoundBox user guides, and POS operational troubleshooting.",
    stageOwnership: "General Product Guidance",
    mcpAgentId: "agent_knowledge_base",
    status: "healthy",
    allowedTools: [
      { toolName: "query_product_documentation", description: "Vector similarity search over SoundBox & POS manuals", actionScope: "READ" },
    ],
    prohibitedTools: [
      { toolName: "view_customer_pii", whyBlocked: "Knowledge queries operate purely on public technical documentation without merchant PII." },
    ],
    n8nWorkflowRef: "WF-RAG-KNOWLEDGE-V2",
    requests24h: 3810,
    avgLatencyMs: 140,
    errorRate: 0.001,
    enforcementStory: "Stateless informational retrieval. Completely decoupled from financial and customer PII stores.",
  },
  {
    id: "policy-risk-agent",
    name: "Policy & Risk Agent",
    category: "Customer Support",
    purpose: "Evaluates governing policies (e.g. PAYMENT-DUPLICATE-V2) and determines autonomous vs human resolution boundaries.",
    stageOwnership: "Governance & Safety Bounds",
    mcpAgentId: "agent_policy_guard",
    status: "healthy",
    allowedTools: [
      { toolName: "search_active_policies", description: "Retrieves active regulatory policies from RAG index", actionScope: "READ" },
      { toolName: "evaluate_refund_threshold", description: "Checks if requested claim exceeds automated ₹10,000 threshold", actionScope: "READ" },
      { toolName: "verify_precedence", description: "Validates that current policy supersedes historical cases", actionScope: "READ" },
    ],
    prohibitedTools: [
      { toolName: "override_rbi_limits", whyBlocked: "Autonomous agents can never override statutory RBI limits; hardcoded safety guard." },
    ],
    n8nWorkflowRef: "WF-POLICY-VERIFIER-V3",
    requests24h: 2190,
    avgLatencyMs: 115,
    errorRate: 0.001,
    enforcementStory: "Acts as an automated compliance auditor. Ensures current policies beat historical precedents and enforces the MCP human sign-off requirement.",
  },
  {
    id: "technical-support-agent",
    name: "Technical Support Agent",
    category: "Customer Support",
    purpose: "SoundBox 4G acoustic telemetry, cellular signal diagnosis, and POS firmware heartbeats.",
    stageOwnership: "IoT Hardware Diagnostics",
    mcpAgentId: "agent_tech_hw_sbx",
    status: "healthy",
    allowedTools: [
      { toolName: "ping_soundbox_acoustic", description: "Sends OTA acoustic heartbeat packet to SoundBox 4G unit", actionScope: "WRITE" },
      { toolName: "fetch_sim_telemetry", description: "Queries M2M carrier signal strength and cell tower ID", actionScope: "READ" },
      { toolName: "trigger_ota_profile_reset", description: "Forces carrier profile renegotiation (Airtel/Jio)", actionScope: "WRITE" },
    ],
    prohibitedTools: [
      { toolName: "erase_device_cryptokeys", whyBlocked: "Cryptographic hardware keys are locked in HSM; agent cannot access flash memory." },
    ],
    n8nWorkflowRef: "WF-IOT-TELEMETRY-SBX",
    requests24h: 1840,
    avgLatencyMs: 165,
    errorRate: 0.004,
    enforcementStory: "Interacts directly with Paytm IoT gateway to perform remote diagnostic pings on sound hardware.",
  },
  {
    id: "payment-capability-agent",
    name: "Payment Capability Agent",
    category: "Customer Support",
    purpose: "Interfaces with NPCI UPI switch and bank clearing houses for dual-debit cross-examination.",
    stageOwnership: "Bank Switch Reconciliation",
    mcpAgentId: "agent_payment_switch",
    status: "healthy",
    allowedTools: [
      { toolName: "query_npci_switch_log", description: "Cross-checks remitter transaction status and response codes (e.g. U69)", actionScope: "READ" },
      { toolName: "inspect_settlement_batch", description: "Checks escrow batch clearance status with clearing bank", actionScope: "READ" },
    ],
    prohibitedTools: [
      { toolName: "auto_execute_payout", whyBlocked: "MCP does not auto-refund; payout releases require human decision." },
    ],
    n8nWorkflowRef: "WF-PAYMENT-SWITCH-RECON",
    requests24h: 1140,
    avgLatencyMs: 240,
    errorRate: 0.003,
    enforcementStory: "Direct read-only window into banking partner switches to confirm whether duplicate debits reached remitter ledgers.",
  },
  {
    id: "human-escalation-agent",
    name: "Human Escalation Agent",
    category: "Customer Support",
    purpose: "Bundles multi-agent evidence into Cosmos-shaped MCP escalation packages for human support ops.",
    stageOwnership: "Human-in-the-Loop Packaging",
    mcpAgentId: "agent_escalation_mcp",
    status: "healthy",
    allowedTools: [
      { toolName: "escalation_create", description: "Assembles evidence JSON, policy ID, and suggested actions into MCP package", actionScope: "WRITE" },
      { toolName: "notify_support_ops", description: "Dispatches high-priority alert to Support Ops queue", actionScope: "WRITE" },
    ],
    prohibitedTools: [
      { toolName: "auto_close_escalation", whyBlocked: "Only human operators can approve or resolve an escalation package." },
    ],
    n8nWorkflowRef: "WF-ESCALATION-PACKAGER",
    requests24h: 700,
    avgLatencyMs: 150,
    errorRate: 0.001,
    enforcementStory: "The definitive bridge between autonomous reasoning and human oversight. Writes immutable records to Cosmos DB.",
  },

  // Sales Multi-Agent System
  {
    id: "outreach-agent",
    name: "Outreach Agent",
    category: "Sales Ops",
    purpose: "Initial merchant lead qualification, WhatsApp introduction, and follow-up audio demos.",
    stageOwnership: "Stage 1 & 2: Outreach & Follow-ups",
    mcpAgentId: "agent_sales_outreach",
    status: "healthy",
    allowedTools: [
      { toolName: "send_intro_whatsapp", description: "Sends certified Paytm SoundBox introduction message", actionScope: "WRITE" },
      { toolName: "log_merchant_interest", description: "Records language preference and store footfall estimate", actionScope: "WRITE" },
    ],
    prohibitedTools: [
      { toolName: "generate_commercial_quote", whyBlocked: "Commercial quotes are strictly owned by Agent2 (Quoting & Negotiation)." },
      { toolName: "skip_to_onboarding", whyBlocked: "Strict stage ownership: No stage skipping permitted." },
    ],
    n8nWorkflowRef: "WF-SALES-OUTREACH-V1",
    requests24h: 1200,
    avgLatencyMs: 130,
    errorRate: 0.002,
    enforcementStory: "Handles first-touch merchant interactions. Hands off to Agent2 once merchant confirms interest.",
  },
  {
    id: "quoting-negotiation-agent",
    name: "Quoting & Negotiation Agent",
    category: "Sales Ops",
    purpose: "Calculates volume pricing, rental waivers, and negotiates MDR terms within pre-approved bands.",
    stageOwnership: "Stage 3 & 4: Quoting & Negotiation",
    mcpAgentId: "agent_sales_quote_negotiate",
    status: "healthy",
    allowedTools: [
      { toolName: "compute_volume_quote", description: "Calculates rental pricing per tier-2 SaaS schedule", actionScope: "READ" },
      { toolName: "generate_merchant_agreement", description: "Drafts master agreement within pre-approved discount limits", actionScope: "WRITE" },
    ],
    prohibitedTools: [
      { toolName: "override_mdr_floor", whyBlocked: "MDR floors are strictly enforced by risk policy; cannot be discounted below 0.0%." },
    ],
    n8nWorkflowRef: "WF-SALES-QUOTE-NEGOTIATE",
    requests24h: 680,
    avgLatencyMs: 190,
    errorRate: 0.001,
    enforcementStory: "Negotiates merchant contracts within algorithmically bounded discount bands. Passes signed deals to Agent3.",
  },
  {
    id: "onboarding-agent",
    name: "Onboarding Agent",
    category: "Sales Ops",
    purpose: "Terminal SIM provisioning, merchant KYC verification, and dynamic QR dispatch.",
    stageOwnership: "Stage 5 & 6: Onboarding & Deployment",
    mcpAgentId: "agent_sales_onboard",
    status: "healthy",
    allowedTools: [
      { toolName: "provision_soundbox_imei", description: "Binds hardware IMEI to merchant MID", actionScope: "WRITE" },
      { toolName: "dispatch_hardware_order", description: "Generates logistics airway bill with Bluedart", actionScope: "WRITE" },
    ],
    prohibitedTools: [
      { toolName: "modify_pricing_terms", whyBlocked: "Pricing terms are immutable post-contract signing." },
    ],
    n8nWorkflowRef: "WF-SALES-ONBOARD-DEPLOY",
    requests24h: 310,
    avgLatencyMs: 210,
    errorRate: 0.001,
    enforcementStory: "Automates terminal fulfillment. Runs live ₹1 test payment verification upon hardware delivery.",
  },
];

export const MOCK_TRACES: Trace[] = [
  {
    traceId: "TRC-2026-90214",
    timestamp: "2026-09-19 16:15:12 IST",
    customerId: "CUST-10291",
    intent: "PAYMENT_DISPUTE_RECONCILIATION",
    agentsCalled: [
      "Customer Support Autonomous Orchestrator",
      "Payment Capability Agent",
      "Policy & Risk Agent",
      "Human Escalation Agent",
    ],
    decision: "escalated_to_human",
    latencyMs: 184,
    status: "success",
    orderId: "ORD-DUP-1001",
    escalationId: "ESC-90214",
    steps: [
      {
        stepNumber: 1,
        phase: "Intent Recognition",
        agent: "Customer Support Autonomous Orchestrator",
        action: "classify_intent",
        status: "SUCCESS",
        inputSummary: "Customer reported: 'Rahul Sharma debited twice ₹1,450 during UPI drop'",
        outputSummary: "Recognized intent: PAYMENT_DISPUTE_RECONCILIATION (Confidence: 0.98)",
        durationMs: 28,
      },
      {
        stepNumber: 2,
        phase: "Specialist Delegation",
        agent: "Customer Support Autonomous Orchestrator",
        action: "delegate_to_specialist",
        status: "SUCCESS",
        inputSummary: "Delegating to PaymentCapabilityAgent and PolicyRiskAgent",
        outputSummary: "Context forwarded with orderId: ORD-DUP-1001",
        durationMs: 12,
      },
      {
        stepNumber: 3,
        phase: "MCP Tool Execution",
        agent: "Payment Capability Agent",
        action: "query_npci_switch_log",
        toolName: "query_npci_switch_log",
        status: "ALLOW",
        inputSummary: "Querying NPCI switch ledger for UTR-428901829001",
        outputSummary: "Switch returned code U69. Dual debits confirmed on remitter switch (TXN-001 settled, TXN-002 reversed/pending).",
        durationMs: 82,
      },
      {
        stepNumber: 4,
        phase: "Validation & Policy",
        agent: "Policy & Risk Agent",
        action: "search_active_policies",
        toolName: "search_active_policies",
        status: "ALLOW",
        inputSummary: "Verifying governing rule for switch code U69",
        outputSummary: "Matched policy: PAYMENT-DUPLICATE-V2 (Section 4.1). Invariant: MCP does not auto-refund; human decision required.",
        durationMs: 34,
      },
      {
        stepNumber: 5,
        phase: "Final Action",
        agent: "Human Escalation Agent",
        action: "escalation_create",
        toolName: "escalation_create",
        status: "ALLOW",
        inputSummary: "Assembling evidence JSON, policy clause, and recommended action",
        outputSummary: "Escalation package ESC-90214 created in Cosmos DB. Assigned to Support Ops.",
        durationMs: 28,
      },
    ],
    rawTraceText: JSON.stringify(
      {
        traceId: "TRC-2026-90214",
        orchestrator: "WF-CS-SUPERVISOR-V4",
        mcpGateway: "https://railway-mcp.internal.corp/mcp",
        customerId: "CUST-10291",
        orderId: "ORD-DUP-1001",
        mcpTokensConsumed: 1840,
        policyEnforced: "PAYMENT-DUPLICATE-V2",
      },
      null,
      2
    ),
  },
  {
    traceId: "TRC-2026-DENY-01",
    timestamp: "2026-09-19 14:02:19 IST",
    customerId: "CUST-20442",
    intent: "UNAUTHORIZED_TOOL_INVOCATION_ATTEMPT",
    agentsCalled: ["Orders & Accounts Agent"],
    decision: "blocked_by_policy",
    latencyMs: 32,
    status: "error",
    orderId: "ORD-82931",
    steps: [
      {
        stepNumber: 1,
        phase: "Specialist Delegation",
        agent: "Customer Support Autonomous Orchestrator",
        action: "delegate_to_specialist",
        status: "SUCCESS",
        inputSummary: "OrdersAgent queried for order status",
        outputSummary: "Order ORD-82931 loaded",
        durationMs: 14,
      },
      {
        stepNumber: 2,
        phase: "MCP Tool Execution",
        agent: "Orders & Accounts Agent",
        action: "payment_refund",
        toolName: "payment_refund",
        status: "DENY",
        inputSummary: "Agent requested tool 'payment_refund' for amount INR 820.00",
        outputSummary: "MCP Gateway DENIED tool call: agent_orders_v2 does not possess privilege 'payment_refund'. Security violation logged.",
        durationMs: 18,
      },
    ],
    rawTraceText: JSON.stringify(
      {
        traceId: "TRC-2026-DENY-01",
        securityAlert: "TOOL_DENY_ENFORCED",
        agentId: "agent_orders_v2",
        attemptedTool: "payment_refund",
        mcpPolicy: "LEAST_PRIVILEGE_STRICT",
        actionTaken: "BLOCKED_BY_MCP_GATEWAY",
      },
      null,
      2
    ),
  },
  {
    traceId: "TRC-2026-88410",
    timestamp: "2026-09-19 12:44:08 IST",
    customerId: "CUST-10291",
    intent: "HARDWARE_TELEMETRY_DIAGNOSTICS",
    agentsCalled: ["Technical Support Agent", "Policy & Risk Agent"],
    decision: "auto_resolved",
    latencyMs: 165,
    status: "success",
    steps: [
      {
        stepNumber: 1,
        phase: "Intent Recognition",
        agent: "Customer Support Autonomous Orchestrator",
        action: "classify_intent",
        status: "SUCCESS",
        inputSummary: "Merchant requested acoustic ping for SoundBox TID-SBX-82931",
        outputSummary: "Intent classified: HARDWARE_TELEMETRY_DIAGNOSTICS",
        durationMs: 22,
      },
      {
        stepNumber: 2,
        phase: "MCP Tool Execution",
        agent: "Technical Support Agent",
        action: "ping_soundbox_acoustic",
        toolName: "ping_soundbox_acoustic",
        status: "ALLOW",
        inputSummary: "Sending OTA heartbeat acoustic test to terminal TID-SBX-82931",
        outputSummary: "ACK received in 138ms. Firmware SBX-v4.2.11-AUTO healthy.",
        durationMs: 120,
      },
      {
        stepNumber: 3,
        phase: "Final Action",
        agent: "Customer Support Autonomous Orchestrator",
        action: "format_reply",
        status: "SUCCESS",
        inputSummary: "Telemetry formatted with battery and signal metrics",
        outputSummary: "Delivered to merchant chat interface.",
        durationMs: 23,
      },
    ],
    rawTraceText: JSON.stringify(
      {
        traceId: "TRC-2026-88410",
        terminalId: "TID-SBX-82931",
        latencyACK: 138,
        result: "HEALTHY",
      },
      null,
      2
    ),
  },
];

export const MOCK_INTEGRATIONS: IntegrationStatus[] = [
  {
    serviceName: "Model Context Protocol (MCP) Gateway",
    envKey: "MCP_BASE_URL",
    maskedUrl: "https://railway-mcp.internal.corp/mcp",
    category: "Model Context Protocol",
    status: "reachable",
    latencyMs: 42,
    lastChecked: "Just now (Live)",
    documentationUrl: "/admin/mcp",
  },
  {
    serviceName: "n8n Customer Support Orchestrator",
    envKey: "N8N_CS_ORCHESTRATOR_URL",
    maskedUrl: "https://n8n.internal.corp/webhook/cs-orchestrator-v1",
    category: "Workflow Automation",
    status: "reachable",
    latencyMs: 65,
    lastChecked: "1 min ago",
  },
  {
    serviceName: "n8n RAG Policy Ingestion Pipeline",
    envKey: "N8N_RAG_INGEST_URL",
    maskedUrl: "https://n8n.internal.corp/webhook/rag-policy-ingest-v1",
    category: "Workflow Automation",
    status: "reachable",
    latencyMs: 88,
    lastChecked: "3 mins ago",
  },
  {
    serviceName: "Azure Cosmos DB (Escalations & Memory)",
    envKey: "AZURE_COSMOS_ENDPOINT",
    maskedUrl: "https://paytm-ai-os-cosmos.documents.azure.com:443/",
    category: "Cloud Data Store",
    status: "configured",
    latencyMs: 18,
    lastChecked: "5 mins ago",
  },
  {
    serviceName: "Azure AI Search (Policy Vector Store)",
    envKey: "AZURE_SEARCH_ENDPOINT",
    maskedUrl: "https://paytm-ai-os-search.search.windows.net",
    category: "AI Services",
    status: "configured",
    latencyMs: 24,
    lastChecked: "5 mins ago",
  },
  {
    serviceName: "Azure OpenAI Service (GPT-4o & Embeddings)",
    envKey: "AZURE_OPENAI_ENDPOINT",
    maskedUrl: "https://paytm-ai-os-openai.openai.azure.com/",
    category: "AI Services",
    status: "configured",
    latencyMs: 140,
    lastChecked: "2 mins ago",
  },
];

let usersStore: AdminUser[] = [
  {
    id: "USR-001",
    name: "Platform Administrator",
    email: "admin.super@company.mock",
    role: "admin",
    department: "Platform Engineering & Security",
    status: "active",
    lastLogin: "Just now",
    mfaEnabled: true,
  },
  {
    id: "USR-002",
    name: "Vikram Mehta",
    email: "support.agent@company.mock",
    role: "support",
    department: "Tier-2 Merchant Dispute & Hardware Operations",
    status: "active",
    lastLogin: "10 mins ago",
    mfaEnabled: true,
  },
  {
    id: "USR-003",
    name: "Priya Iyer",
    email: "sales.ops@company.mock",
    role: "sales_ops",
    department: "Merchant Pipeline & Multi-Agent Revenue Ops",
    status: "active",
    lastLogin: "1 hour ago",
    mfaEnabled: true,
  },
  {
    id: "USR-004",
    name: "Devashish Roy",
    email: "policy.owner@company.mock",
    role: "policy_owner",
    department: "Regulatory Compliance & AI Policy Governance",
    status: "active",
    lastLogin: "2 hours ago",
    mfaEnabled: true,
  },
  {
    id: "USR-005",
    name: "Rajesh Kumar (Merchant)",
    email: "rajesh.retail@merchants.paytm.mock",
    role: "customer",
    department: "Rajesh Supermarket & Provision Store (MID-992810482)",
    status: "active",
    lastLogin: "Today, 16:12 IST",
    mfaEnabled: false,
  },
];

export function getUsersStore(): AdminUser[] {
  return usersStore;
}

export function addUserToStore(user: Omit<AdminUser, "id" | "lastLogin">): AdminUser {
  const newUser: AdminUser = {
    ...user,
    id: `USR-${String(usersStore.length + 1).padStart(3, "0")}`,
    lastLogin: "Never",
  };
  usersStore = [newUser, ...usersStore];
  return newUser;
}

export function updateUserRoleInStore(userId: string, newRole: AdminUser["role"]): boolean {
  const user = usersStore.find((u) => u.id === userId);
  if (user) {
    user.role = newRole;
    return true;
  }
  return false;
}

export const MOCK_AUDIT_LOGS: AuditEvent[] = [
  {
    id: "AUD-991",
    timestamp: "2026-09-19 16:15:15 IST",
    actor: "Human Escalation Agent",
    action: "MCP_PACKAGE_CREATE",
    target: "ESC-90214",
    severity: "INFO",
    details: "Escalation package created for dual-debit ORD-DUP-1001 under policy PAYMENT-DUPLICATE-V2.",
  },
  {
    id: "AUD-990",
    timestamp: "2026-09-19 14:02:19 IST",
    actor: "MCP Gateway Guard",
    action: "TOOL_DENY_ENFORCED",
    target: "agent_orders_v2 :: payment_refund",
    severity: "WARNING",
    details: "Blocked unauthorized tool call: Orders & Accounts Agent attempted payment_refund on ORD-82931.",
  },
  {
    id: "AUD-989",
    timestamp: "2026-09-19 11:20:00 IST",
    actor: "Devashish Roy (policy_owner)",
    action: "POLICY_INGEST_PROMOTE",
    target: "PAYMENT-DUPLICATE-V2 (v2.4.2)",
    severity: "INFO",
    details: "Re-ingested regulatory markdown into RAG vector index. Vector embeddings updated.",
  },
  {
    id: "AUD-988",
    timestamp: "2026-09-18 17:00:00 IST",
    actor: "Agent1-Outreach",
    action: "STAGE_PROGRESSION",
    target: "LEAD-401 (Aroma Coffee)",
    severity: "INFO",
    details: "Handed off lead from Outreach to Agent2-QuoteNegotiate with structured stage logs.",
  },
  {
    id: "AUD-987",
    timestamp: "2026-09-18 10:15:00 IST",
    actor: "Security Admin",
    action: "INTEGRATION_KEY_ROTATION",
    target: "AZURE_SEARCH_ENDPOINT",
    severity: "INFO",
    details: "Automated rotation of secondary API key completed successfully.",
  },
];
